CREATE TABLE USER (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(150) NOT NULL,
  EMAIL VARCHAR(254),
  DISPLAY_NAME VARCHAR(255),
  AVATAR_URL VARCHAR(1024),
  AUTHORITY VARCHAR(32) NOT NULL DEFAULT 'USER',
  STATUS VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  LAST_LOGIN_AT TIMESTAMP,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX UK_USERS_USERNAME ON USER(USERNAME);
CREATE TABLE REPOSITORY (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  PATH VARCHAR(255) NOT NULL,
  REPOSITORY_TYPE VARCHAR(32) NOT NULL DEFAULT 'GIT',
  OWNER_TYPE VARCHAR(32),
  OWNER_ID BIGINT,
  CREDENTIAL_ID VARCHAR(128),
  CLONE_PATH VARCHAR(512),
  DESCRIPTION VARCHAR(2000),
  DEFAULT_BRANCH VARCHAR(255) NOT NULL,
  VISIBILITY VARCHAR(32) NOT NULL,
  STATUS VARCHAR(32) NOT NULL DEFAULT 'REGISTERED',
  LAST_SYNCED_AT TIMESTAMP,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX UK_REPOSITORY_PATH ON REPOSITORY(PATH);
CREATE TABLE PULL_REQUEST (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  REPOSITORY_ID BIGINT NOT NULL,
  SOURCE_BRANCH VARCHAR(255) NOT NULL,
  SOURCE_HEAD VARCHAR(64) NOT NULL,
  TARGET_BRANCH VARCHAR(255) NOT NULL,
  TARGET_HEAD VARCHAR(64) NOT NULL,
  STATUS VARCHAR(32) NOT NULL,
  TARGET_DRIFTED BOOLEAN NOT NULL DEFAULT FALSE,
  PREVIOUS_TARGET_HEAD VARCHAR(64),
  CURRENT_TARGET_HEAD VARCHAR(64),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IX_PULL_REQUEST_REPOSITORY_STATUS ON PULL_REQUEST(REPOSITORY_ID, STATUS);
CREATE INDEX IX_PULL_REQUEST_REPOSITORY_TARGET ON PULL_REQUEST(REPOSITORY_ID, TARGET_BRANCH);