package io.jgitkins.server.collaboration.application.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import io.jgitkins.server.collaboration.adapter.out.persistence.OrganizeMemberPersistenceAdapter;
import io.jgitkins.server.collaboration.adapter.out.persistence.OrganizePersistenceAdapter;
import io.jgitkins.server.collaboration.application.dto.command.OrganizeCreationCommand;
import io.jgitkins.server.collaboration.application.dto.result.OrganizeCreationResult;
import io.jgitkins.server.collaboration.application.mapper.OrganizeApplicationMapper;
import io.jgitkins.server.collaboration.application.port.out.DomainEventPublisher;
import io.jgitkins.server.collaboration.application.port.out.OrganizeMemberPersistencePort;
import io.jgitkins.server.collaboration.application.validate.OrganizeValidator;
import io.jgitkins.server.collaboration.domain.entity.OrganizeMember;
import io.jgitkins.server.collaboration.domain.vo.OrganizeId;
import io.jgitkins.server.collaboration.domain.vo.OrganizeMemberRole;
import io.jgitkins.server.collaboration.domain.vo.OrganizeName;
import io.jgitkins.server.collaboration.domain.vo.OrganizeOwnerId;
import io.jgitkins.server.collaboration.adapter.out.persistence.support.OrganizeDomainMapper;
import io.jgitkins.server.collaboration.adapter.out.persistence.support.OrganizeMemberDomainMapper;
import io.jgitkins.server.collaboration.adapter.out.persistence.mapper.OrganizeEntityMbgMapper;
import io.jgitkins.server.collaboration.adapter.out.persistence.mapper.OrganizeMemberEntityMbgMapper;
import java.time.LocalDateTime;
import javax.sql.DataSource;
import org.apache.ibatis.session.SqlSessionFactory;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.mybatis.spring.SqlSessionFactoryBean;
import org.mybatis.spring.SqlSessionTemplate;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabase;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;
import org.springframework.transaction.support.TransactionTemplate;

class OrganizeCreationMembershipBootstrapTest {

    private EmbeddedDatabase dataSource;
    private JdbcTemplate jdbcTemplate;
    private OrganizePersistenceAdapter organizeRepository;
    private OrganizeMemberPersistenceAdapter memberRepository;
    private OrganizeService organizeService;
    private TransactionTemplate transactionTemplate;

    @BeforeEach
    void setUp() throws Exception {
        dataSource = new EmbeddedDatabaseBuilder().generateUniqueName(true).setType(EmbeddedDatabaseType.H2).build();
        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("create table ORGANIZE (ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, NAME VARCHAR(255) NOT NULL, PATH VARCHAR(255) NOT NULL, OWNER_ID BIGINT NOT NULL, CREATED_AT TIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP NOT NULL, DESCRIPTION CLOB)");
        jdbcTemplate.execute("create table ORGANIZE_MEMBER (ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ORGANIZE_ID BIGINT NOT NULL, USER_ID BIGINT NOT NULL, ROLE VARCHAR(32) NOT NULL, JOINED_AT TIMESTAMP NOT NULL, UNIQUE (ORGANIZE_ID, USER_ID))");

        SqlSessionFactory factory = sqlSessionFactory(dataSource);
        organizeRepository = new OrganizePersistenceAdapter(
                new SqlSessionTemplate(factory).getMapper(OrganizeEntityMbgMapper.class),
                org.mapstruct.factory.Mappers.getMapper(OrganizeDomainMapper.class));
        memberRepository = new OrganizeMemberPersistenceAdapter(
                new SqlSessionTemplate(factory).getMapper(OrganizeMemberEntityMbgMapper.class),
                org.mapstruct.factory.Mappers.getMapper(OrganizeMemberDomainMapper.class));
        DomainEventPublisher domainEventPublisher = Mockito.mock(DomainEventPublisher.class);
        OrganizeValidator organizeValidator = Mockito.mock(OrganizeValidator.class);
        OrganizeApplicationMapper organizeApplicationMapper = Mockito.mock(OrganizeApplicationMapper.class);
        Mockito.when(organizeApplicationMapper.toDto(Mockito.any())).thenReturn(
                new OrganizeCreationResult(1L, "team", null, 7L, null, null));
        organizeService = new OrganizeService(
                organizeRepository, memberRepository, domainEventPublisher,
                organizeValidator, organizeApplicationMapper,
                Mockito.mock(io.jgitkins.server.collaboration.application.port.out
                        .OrganizeMembershipQueryPort.class),
                Mockito.mock(io.jgitkins.server.collaboration.application.port.out
                        .OrganizeOwnedRepositoryCountPort.class));
        transactionTemplate = new TransactionTemplate(new DataSourceTransactionManager(dataSource));
    }

    @AfterEach
    void tearDown() {
        dataSource.shutdown();
    }

    @Test
    void organizationAndCreatorOwnerMembershipCommitTogether() {
        transactionTemplate.executeWithoutResult(status -> {
            organizeService.createOrganize(new OrganizeCreationCommand("team", "description", 7L));
        });

        assertThat(jdbcTemplate.queryForObject("select count(*) from ORGANIZE", Integer.class)).isEqualTo(1);
        assertThat(jdbcTemplate.queryForObject("select count(*) from ORGANIZE_MEMBER", Integer.class)).isEqualTo(1);
        assertThat(jdbcTemplate.queryForObject("select ORGANIZE_ID from ORGANIZE_MEMBER", Long.class)).isEqualTo(1L);
    }

    @Test
    void membershipFailureRollsBackOrganizationWrite() {
        assertThatThrownBy(() -> transactionTemplate.executeWithoutResult(status -> {
            organizeService.createOrganize(new OrganizeCreationCommand("rollback", "description", 7L));
            throw new IllegalStateException("required membership write failed");
        })).isInstanceOf(IllegalStateException.class);

        assertThat(jdbcTemplate.queryForObject("select count(*) from ORGANIZE", Integer.class)).isZero();
        assertThat(jdbcTemplate.queryForObject("select count(*) from ORGANIZE_MEMBER", Integer.class)).isZero();
    }

    @Test
    void memberPersistenceFailureRollsBackOrganizationWrite() {
        DomainEventPublisher domainEventPublisher = Mockito.mock(DomainEventPublisher.class);
        OrganizeValidator organizeValidator = Mockito.mock(OrganizeValidator.class);
        OrganizeApplicationMapper organizeApplicationMapper = Mockito.mock(OrganizeApplicationMapper.class);
        OrganizeMemberPersistencePort failingMemberPersistence = Mockito.mock(OrganizeMemberPersistencePort.class);
        Mockito.doThrow(new IllegalStateException("membership insert failed"))
                .when(failingMemberPersistence).save(Mockito.any());
        OrganizeService failingService = new OrganizeService(
                organizeRepository, failingMemberPersistence, domainEventPublisher,
                organizeValidator, organizeApplicationMapper,
                Mockito.mock(io.jgitkins.server.collaboration.application.port.out
                        .OrganizeMembershipQueryPort.class),
                Mockito.mock(io.jgitkins.server.collaboration.application.port.out
                        .OrganizeOwnedRepositoryCountPort.class));

        assertThatThrownBy(() -> transactionTemplate.executeWithoutResult(status ->
                failingService.createOrganize(new OrganizeCreationCommand("member-failure", "description", 7L))))
                .isInstanceOf(IllegalStateException.class)
                .hasMessage("membership insert failed");

        assertThat(jdbcTemplate.queryForObject("select count(*) from ORGANIZE", Integer.class)).isZero();
        assertThat(jdbcTemplate.queryForObject("select count(*) from ORGANIZE_MEMBER", Integer.class)).isZero();
    }

    private SqlSessionFactory sqlSessionFactory(DataSource dataSource) throws Exception {
        SqlSessionFactoryBean factoryBean = new SqlSessionFactoryBean();
        factoryBean.setDataSource(dataSource);
        factoryBean.setMapperLocations(
                new ClassPathResource("mapper/mbg/OrganizeEntityMbgMapper.xml"),
                new ClassPathResource("mapper/mbg/OrganizeMemberEntityMbgMapper.xml"));
        factoryBean.setConfiguration(new org.apache.ibatis.session.Configuration());
        factoryBean.afterPropertiesSet();
        return factoryBean.getObject();
    }

    private static final class OrganizeWithoutEventFactory {
        private static io.jgitkins.server.collaboration.domain.aggregate.Organize create(String name, Long ownerId) {
            return io.jgitkins.server.collaboration.domain.aggregate.Organize.createWithoutEvent(
                    null, OrganizeName.from(name), OrganizeOwnerId.of(ownerId), "description", LocalDateTime.now());
        }
    }
}
